name: require pull request

on:
  push:
    branches: 
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running!"
